/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Event {
  description: string;
  id: Generated<number>;
  title: string;
}

export interface Item {
  description: string | null;
  id: Generated<number>;
  listId: number;
  name: string;
  url: string;
}

export interface List {
  eventId: number;
  id: Generated<number>;
  userId: string;
}

export interface NeonAuthUsersSync {
  createdAt: Generated<Timestamp | null>;
  deletedAt: Timestamp | null;
  email: Generated<string | null>;
  id: Generated<string>;
  name: Generated<string | null>;
  rawJson: Json;
  updatedAt: Timestamp | null;
}

export interface DB {
  event: Event;
  item: Item;
  list: List;
  "neonAuth.usersSync": NeonAuthUsersSync;
}
